/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Skyapi.Model
{
    /// <summary>
    /// TransactionVerbose has readable transaction data. It adds TransactionStatus to a BlockTransactionVerbose
    /// </summary>
    [DataContract]
    public class TransactionTxn : IEquatable<TransactionTxn>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionTxn" /> class.
        /// </summary>
        /// <param name="innerHash">innerHash.</param>
        /// <param name="inputs">inputs.</param>
        /// <param name="length">length.</param>
        /// <param name="outputs">outputs.</param>
        /// <param name="sigs">sigs.</param>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="txid">txid.</param>
        /// <param name="type">type.</param>
        public TransactionTxn(string innerHash = default(string), List<string> inputs = default(List<string>),
            int? length = default(int?), List<TransactionOutput> outputs = default(List<TransactionOutput>),
            List<string> sigs = default(List<string>), long? timestamp = default(long?), string txid = default(string),
            int? type = default(int?))
        {
            InnerHash = innerHash;
            Inputs = inputs;
            Length = length;
            Outputs = outputs;
            Sigs = sigs;
            Timestamp = timestamp;
            Txid = txid;
            Type = type;
        }

        /// <summary>
        /// Gets or Sets InnerHash
        /// </summary>
        [DataMember(Name = "inner_hash", EmitDefaultValue = false)]
        public string InnerHash { get; set; }

        /// <summary>
        /// Gets or Sets Inputs
        /// </summary>
        [DataMember(Name = "inputs", EmitDefaultValue = false)]
        public List<string> Inputs { get; set; }

        /// <summary>
        /// Gets or Sets Length
        /// </summary>
        [DataMember(Name = "length", EmitDefaultValue = false)]
        public int? Length { get; set; }

        /// <summary>
        /// Gets or Sets Outputs
        /// </summary>
        [DataMember(Name = "outputs", EmitDefaultValue = false)]
        public List<TransactionOutput> Outputs { get; set; }

        /// <summary>
        /// Gets or Sets Sigs
        /// </summary>
        [DataMember(Name = "sigs", EmitDefaultValue = false)]
        public List<string> Sigs { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name = "timestamp", EmitDefaultValue = false)]
        public long? Timestamp { get; set; }

        /// <summary>
        /// Gets or Sets Txid
        /// </summary>
        [DataMember(Name = "txid", EmitDefaultValue = false)]
        public string Txid { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public int? Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionTxn {\n");
            sb.Append("  InnerHash: ").Append(InnerHash).Append("\n");
            sb.Append("  Inputs: ").Append(Inputs).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Outputs: ").Append(Outputs).Append("\n");
            sb.Append("  Sigs: ").Append(Sigs).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Txid: ").Append(Txid).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TransactionTxn);
        }

        /// <summary>
        /// Returns true if TransactionTxn instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionTxn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionTxn input)
        {
            if (input == null)
                return false;

            return
                (
                    InnerHash == input.InnerHash ||
                    (InnerHash != null &&
                     InnerHash.Equals(input.InnerHash))
                ) &&
                (
                    Inputs == input.Inputs ||
                    Inputs != null &&
                    input.Inputs != null &&
                    Inputs.SequenceEqual(input.Inputs)
                ) &&
                (
                    Length == input.Length ||
                    (Length != null &&
                     Length.Equals(input.Length))
                ) &&
                (
                    Outputs == input.Outputs ||
                    Outputs != null &&
                    input.Outputs != null &&
                    Outputs.SequenceEqual(input.Outputs)
                ) &&
                (
                    Sigs == input.Sigs ||
                    Sigs != null &&
                    input.Sigs != null &&
                    Sigs.SequenceEqual(input.Sigs)
                ) &&
                (
                    Timestamp == input.Timestamp ||
                    (Timestamp != null &&
                     Timestamp.Equals(input.Timestamp))
                ) &&
                (
                    Txid == input.Txid ||
                    (Txid != null &&
                     Txid.Equals(input.Txid))
                ) &&
                (
                    Type == input.Type ||
                    (Type != null &&
                     Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (InnerHash != null)
                    hashCode = hashCode * 59 + InnerHash.GetHashCode();
                if (Inputs != null)
                    hashCode = hashCode * 59 + Inputs.GetHashCode();
                if (Length != null)
                    hashCode = hashCode * 59 + Length.GetHashCode();
                if (Outputs != null)
                    hashCode = hashCode * 59 + Outputs.GetHashCode();
                if (Sigs != null)
                    hashCode = hashCode * 59 + Sigs.GetHashCode();
                if (Timestamp != null)
                    hashCode = hashCode * 59 + Timestamp.GetHashCode();
                if (Txid != null)
                    hashCode = hashCode * 59 + Txid.GetHashCode();
                if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext)
        {
            yield break;
        }
    }
}