/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing ApiV1WalletsEntries
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiV1WalletsEntriesTests
    {
        // TODO uncomment below to declare an instance variable for ApiV1WalletsEntries
        //private ApiV1WalletsEntries instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiV1WalletsEntries
            //instance = new ApiV1WalletsEntries();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiV1WalletsEntries
        /// </summary>
        [Test]
        public void ApiV1WalletsEntriesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiV1WalletsEntries
            //Assert.IsInstanceOfType<ApiV1WalletsEntries> (instance, "variable 'instance' is a ApiV1WalletsEntries");
        }


        /// <summary>
        /// Test the property 'PublicKey'
        /// </summary>
        [Test]
        public void PublicKeyTest()
        {
            // TODO unit test for the property 'PublicKey'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
