/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing ApiV1WalletsMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ApiV1WalletsMetaTests
    {
        // TODO uncomment below to declare an instance variable for ApiV1WalletsMeta
        //private ApiV1WalletsMeta instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiV1WalletsMeta
            //instance = new ApiV1WalletsMeta();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiV1WalletsMeta
        /// </summary>
        [Test]
        public void ApiV1WalletsMetaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiV1WalletsMeta
            //Assert.IsInstanceOfType<ApiV1WalletsMeta> (instance, "variable 'instance' is a ApiV1WalletsMeta");
        }


        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Test]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
        /// <summary>
        /// Test the property 'Encrypted'
        /// </summary>
        [Test]
        public void EncryptedTest()
        {
            // TODO unit test for the property 'Encrypted'
        }
        /// <summary>
        /// Test the property 'CryptoType'
        /// </summary>
        [Test]
        public void CryptoTypeTest()
        {
            // TODO unit test for the property 'CryptoType'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Coin'
        /// </summary>
        [Test]
        public void CoinTest()
        {
            // TODO unit test for the property 'Coin'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

    }

}
