/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing BlockVerboseSchemaHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BlockVerboseSchemaHeaderTests
    {
        // TODO uncomment below to declare an instance variable for BlockVerboseSchemaHeader
        //private BlockVerboseSchemaHeader instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BlockVerboseSchemaHeader
            //instance = new BlockVerboseSchemaHeader();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BlockVerboseSchemaHeader
        /// </summary>
        [Test]
        public void BlockVerboseSchemaHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BlockVerboseSchemaHeader
            //Assert.IsInstanceOfType<BlockVerboseSchemaHeader> (instance, "variable 'instance' is a BlockVerboseSchemaHeader");
        }


        /// <summary>
        /// Test the property 'Seq'
        /// </summary>
        [Test]
        public void SeqTest()
        {
            // TODO unit test for the property 'Seq'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'BlockHash'
        /// </summary>
        [Test]
        public void BlockHashTest()
        {
            // TODO unit test for the property 'BlockHash'
        }
        /// <summary>
        /// Test the property 'PreviousBlockHash'
        /// </summary>
        [Test]
        public void PreviousBlockHashTest()
        {
            // TODO unit test for the property 'PreviousBlockHash'
        }
        /// <summary>
        /// Test the property 'TxBodyHash'
        /// </summary>
        [Test]
        public void TxBodyHashTest()
        {
            // TODO unit test for the property 'TxBodyHash'
        }
        /// <summary>
        /// Test the property 'UxHash'
        /// </summary>
        [Test]
        public void UxHashTest()
        {
            // TODO unit test for the property 'UxHash'
        }

    }

}
