/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing InlineObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineObjectTests
    {
        // TODO uncomment below to declare an instance variable for InlineObject
        //private InlineObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject
            //instance = new InlineObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject
        /// </summary>
        [Test]
        public void InlineObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject
            //Assert.IsInstanceOfType<InlineObject> (instance, "variable 'instance' is a InlineObject");
        }


        /// <summary>
        /// Test the property 'ChangeAddress'
        /// </summary>
        [Test]
        public void ChangeAddressTest()
        {
            // TODO unit test for the property 'ChangeAddress'
        }
        /// <summary>
        /// Test the property 'HoursSelection'
        /// </summary>
        [Test]
        public void HoursSelectionTest()
        {
            // TODO unit test for the property 'HoursSelection'
        }
        /// <summary>
        /// Test the property 'IgnoreUnconfirmed'
        /// </summary>
        [Test]
        public void IgnoreUnconfirmedTest()
        {
            // TODO unit test for the property 'IgnoreUnconfirmed'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Wallet'
        /// </summary>
        [Test]
        public void WalletTest()
        {
            // TODO unit test for the property 'Wallet'
        }

    }

}
