/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2005
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2005Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2005
        //private InlineResponse2005 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2005
            //instance = new InlineResponse2005();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2005
        /// </summary>
        [Test]
        public void InlineResponse2005InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2005
            //Assert.IsInstanceOfType<InlineResponse2005> (instance, "variable 'instance' is a InlineResponse2005");
        }


        /// <summary>
        /// Test the property 'Branch'
        /// </summary>
        [Test]
        public void BranchTest()
        {
            // TODO unit test for the property 'Branch'
        }
        /// <summary>
        /// Test the property 'Commit'
        /// </summary>
        [Test]
        public void CommitTest()
        {
            // TODO unit test for the property 'Commit'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
