/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2006
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2006Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2006
        //private InlineResponse2006 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2006
            //instance = new InlineResponse2006();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2006
        /// </summary>
        [Test]
        public void InlineResponse2006InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2006
            //Assert.IsInstanceOfType<InlineResponse2006> (instance, "variable 'instance' is a InlineResponse2006");
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
