/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing NetworkConnectionSchemaUnconfirmedVerifyTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NetworkConnectionSchemaUnconfirmedVerifyTransactionTests
    {
        // TODO uncomment below to declare an instance variable for NetworkConnectionSchemaUnconfirmedVerifyTransaction
        //private NetworkConnectionSchemaUnconfirmedVerifyTransaction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NetworkConnectionSchemaUnconfirmedVerifyTransaction
            //instance = new NetworkConnectionSchemaUnconfirmedVerifyTransaction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NetworkConnectionSchemaUnconfirmedVerifyTransaction
        /// </summary>
        [Test]
        public void NetworkConnectionSchemaUnconfirmedVerifyTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NetworkConnectionSchemaUnconfirmedVerifyTransaction
            //Assert.IsInstanceOfType<NetworkConnectionSchemaUnconfirmedVerifyTransaction> (instance, "variable 'instance' is a NetworkConnectionSchemaUnconfirmedVerifyTransaction");
        }


        /// <summary>
        /// Test the property 'BurnFactor'
        /// </summary>
        [Test]
        public void BurnFactorTest()
        {
            // TODO unit test for the property 'BurnFactor'
        }
        /// <summary>
        /// Test the property 'MaxDecimals'
        /// </summary>
        [Test]
        public void MaxDecimalsTest()
        {
            // TODO unit test for the property 'MaxDecimals'
        }
        /// <summary>
        /// Test the property 'MaxTransactionSize'
        /// </summary>
        [Test]
        public void MaxTransactionSizeTest()
        {
            // TODO unit test for the property 'MaxTransactionSize'
        }

    }

}
