/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing TransactionEncodedS
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionEncodedSTests
    {
        // TODO uncomment below to declare an instance variable for TransactionEncodedS
        //private TransactionEncodedS instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionEncodedS
            //instance = new TransactionEncodedS();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionEncodedS
        /// </summary>
        [Test]
        public void TransactionEncodedSInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionEncodedS
            //Assert.IsInstanceOfType<TransactionEncodedS> (instance, "variable 'instance' is a TransactionEncodedS");
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'EncodedTransaction'
        /// </summary>
        [Test]
        public void EncodedTransactionTest()
        {
            // TODO unit test for the property 'EncodedTransaction'
        }

    }

}
