/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing TransactionVerboseTxn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionVerboseTxnTests
    {
        // TODO uncomment below to declare an instance variable for TransactionVerboseTxn
        //private TransactionVerboseTxn instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionVerboseTxn
            //instance = new TransactionVerboseTxn();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionVerboseTxn
        /// </summary>
        [Test]
        public void TransactionVerboseTxnInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionVerboseTxn
            //Assert.IsInstanceOfType<TransactionVerboseTxn> (instance, "variable 'instance' is a TransactionVerboseTxn");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'InnerHash'
        /// </summary>
        [Test]
        public void InnerHashTest()
        {
            // TODO unit test for the property 'InnerHash'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Test]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Test]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }
        /// <summary>
        /// Test the property 'Sigs'
        /// </summary>
        [Test]
        public void SigsTest()
        {
            // TODO unit test for the property 'Sigs'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Txid'
        /// </summary>
        [Test]
        public void TxidTest()
        {
            // TODO unit test for the property 'Txid'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
