/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing TransactionVerifyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionVerifyRequestTests
    {
        // TODO uncomment below to declare an instance variable for TransactionVerifyRequest
        //private TransactionVerifyRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionVerifyRequest
            //instance = new TransactionVerifyRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionVerifyRequest
        /// </summary>
        [Test]
        public void TransactionVerifyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionVerifyRequest
            //Assert.IsInstanceOfType<TransactionVerifyRequest> (instance, "variable 'instance' is a TransactionVerifyRequest");
        }


        /// <summary>
        /// Test the property 'Unsigned'
        /// </summary>
        [Test]
        public void UnsignedTest()
        {
            // TODO unit test for the property 'Unsigned'
        }
        /// <summary>
        /// Test the property 'EncodedTransaction'
        /// </summary>
        [Test]
        public void EncodedTransactionTest()
        {
            // TODO unit test for the property 'EncodedTransaction'
        }

    }

}
