/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing TransactionVerboseTxnInputs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransactionVerboseTxnInputsTests
    {
        // TODO uncomment below to declare an instance variable for TransactionVerboseTxnInputs
        //private TransactionVerboseTxnInputs instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionVerboseTxnInputs
            //instance = new TransactionVerboseTxnInputs();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionVerboseTxnInputs
        /// </summary>
        [Test]
        public void TransactionVerboseTxnInputsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransactionVerboseTxnInputs
            //Assert.IsInstanceOfType<TransactionVerboseTxnInputs> (instance, "variable 'instance' is a TransactionVerboseTxnInputs");
        }


        /// <summary>
        /// Test the property 'Uxid'
        /// </summary>
        [Test]
        public void UxidTest()
        {
            // TODO unit test for the property 'Uxid'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Test]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Coins'
        /// </summary>
        [Test]
        public void CoinsTest()
        {
            // TODO unit test for the property 'Coins'
        }
        /// <summary>
        /// Test the property 'Hours'
        /// </summary>
        [Test]
        public void HoursTest()
        {
            // TODO unit test for the property 'Hours'
        }
        /// <summary>
        /// Test the property 'CalculatedHours'
        /// </summary>
        [Test]
        public void CalculatedHoursTest()
        {
            // TODO unit test for the property 'CalculatedHours'
        }

    }

}
