/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Skyapi.Api;
using Skyapi.Model;
using Skyapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Skyapi.Test
{
    /// <summary>
    ///  Class for testing WalletTransactionRequestHoursSelection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WalletTransactionRequestHoursSelectionTests
    {
        // TODO uncomment below to declare an instance variable for WalletTransactionRequestHoursSelection
        //private WalletTransactionRequestHoursSelection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WalletTransactionRequestHoursSelection
            //instance = new WalletTransactionRequestHoursSelection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WalletTransactionRequestHoursSelection
        /// </summary>
        [Test]
        public void WalletTransactionRequestHoursSelectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WalletTransactionRequestHoursSelection
            //Assert.IsInstanceOfType<WalletTransactionRequestHoursSelection> (instance, "variable 'instance' is a WalletTransactionRequestHoursSelection");
        }


        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'ShareFactor'
        /// </summary>
        [Test]
        public void ShareFactorTest()
        {
            // TODO unit test for the property 'ShareFactor'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
