#!/bin/bash

# This are the git ENV vars present at this point for the build process.
# more on that in https://docs.docker.com/docker-cloud/builds/advanced
#
# SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
# SOURCE_COMMIT: the SHA1 hash of the commit being tested.
# COMMIT_MSG: the message from the commit being tested and built.
# DOCKERFILE_PATH: the dockerfile currently being built.
# DOCKER_REPO: the name of the Docker repository being built.
# CACHE_TAG: the Docker repository tag being built.
# IMAGE_NAME: the name and tag of the Docker repository being built.
#             (This variable is a combination of DOCKER_REPO:CACHE_TAG.)
# VS_EXTENSIONS: Visual Studio Code extensions to add on docker image,
#                only if base image is not CLI purpose.

echo "Build hook running"

ls ../../../gopath/src/github.com/skycoin/skycoin/

# Build :develop tag
docker build --build-arg BDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg SCOMMIT=$SOURCE_COMMIT \
             -f $DOCKERFILE_PATH \
             -t "$IMAGE_NAME" .

# Build :dind, :vscode and :vscode-dind tag
# Only build if docker tag is develop
if [ "$CACHE_TAG" == "develop" ]; then
  docker build --build-arg IMAGE_FROM="skycoin/skycoindev-cli:dind" \
               --build-arg BDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
               --build-arg SCOMMIT=$SOURCE_COMMIT \
               -f $DOCKERFILE_PATH \
               -t "$DOCKER_REPO:dind" .

  docker build --build-arg IMAGE_FROM="$IMAGE_NAME" \
               --build-arg BDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
               --build-arg SCOMMIT=$SOURCE_COMMIT \
               --build-arg VS_EXTENSIONS="ms-vscode.csharp Leopotam.csharpfixformat jchannon.csharpextensions k--kato.docomment formulahendry.dotnet" \
               -f ../../../gopath/src/github.com/skycoin/skycoin/docker/images/dev-vscode/Dockerfile \
               -t "$DOCKER_REPO:vscode" .

  docker build --build-arg IMAGE_FROM="$DOCKER_REPO:dind" \
               --build-arg BDATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
               --build-arg SCOMMIT=$SOURCE_COMMIT \
               --build-arg VS_EXTENSIONS="ms-vscode.csharp Leopotam.csharpfixformat jchannon.csharpextensions k--kato.docomment formulahendry.dotnet" \
               -f ../../../gopath/src/github.com/skycoin/skycoin/docker/images/dev-vscode/Dockerfile \
               -t "$DOCKER_REPO:vscode-dind" .
fi
