//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace skycoin {

public class coin__UxBody : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal coin__UxBody(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(coin__UxBody obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~coin__UxBody() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          skycoinPINVOKE.delete_coin__UxBody(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void SetSrcTransaction(cipher_SHA256 o) {
    skycoinPINVOKE.coin__UxBody_SetSrcTransaction(swigCPtr, cipher_SHA256.getCPtr(o));
  }

  public SWIGTYPE_p_GoUint8_ SrcTransaction {
    set {
      skycoinPINVOKE.set_coin__UxBody_SrcTransaction(swigCPtr, SWIGTYPE_p_GoUint8_.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = skycoinPINVOKE.get_coin__UxBody_SrcTransaction(swigCPtr);
      SWIGTYPE_p_GoUint8_ ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_GoUint8_(cPtr, false);
      return ret;
    } 
  }

  public cipher__Address Address {
    set {
      skycoinPINVOKE.set_coin__UxBody_Address(swigCPtr, cipher__Address.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = skycoinPINVOKE.get_coin__UxBody_Address(swigCPtr);
      cipher__Address ret = (cPtr == global::System.IntPtr.Zero) ? null : new cipher__Address(cPtr, false);
      return ret;
    } 
  }

  public ulong Coins {
    set {
      skycoinPINVOKE.set_coin__UxBody_Coins(swigCPtr, value);
    } 
    get {
      ulong ret = skycoinPINVOKE.get_coin__UxBody_Coins(swigCPtr);
      return ret;
    } 
  }

  public ulong Hours {
    set {
      skycoinPINVOKE.set_coin__UxBody_Hours(swigCPtr, value);
    } 
    get {
      ulong ret = skycoinPINVOKE.get_coin__UxBody_Hours(swigCPtr);
      return ret;
    } 
  }

  public coin__UxBody() : this(skycoinPINVOKE.new_coin__UxBody(), true) {
  }

}

}
