//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace skycoin {

public class coin__Transaction : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal coin__Transaction(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(coin__Transaction obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~coin__Transaction() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          skycoinPINVOKE.delete_coin__Transaction(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int setInnerHash(cipher_SHA256 h) {
    int ret = skycoinPINVOKE.coin__Transaction_setInnerHash(swigCPtr, cipher_SHA256.getCPtr(h));
    if (skycoinPINVOKE.SWIGPendingException.Pending) throw skycoinPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public cipher_SHA256 GetInnerHash() {
    cipher_SHA256 ret = new cipher_SHA256(skycoinPINVOKE.coin__Transaction_GetInnerHash(swigCPtr), true);
    return ret;
  }

  public int isEqual(coin__Transaction t) {
    int ret = skycoinPINVOKE.coin__Transaction_isEqual(swigCPtr, coin__Transaction.getCPtr(t));
    return ret;
  }

  public int Length {
    set {
      skycoinPINVOKE.set_coin__Transaction_Length(swigCPtr, value);
    } 
    get {
      int ret = skycoinPINVOKE.get_coin__Transaction_Length(swigCPtr);
      return ret;
    } 
  }

  public sbyte Type {
    set {
      skycoinPINVOKE.set_coin__Transaction_Type(swigCPtr, value);
    } 
    get {
      sbyte ret = skycoinPINVOKE.get_coin__Transaction_Type(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_GoUint8_ InnerHash {
    set {
      skycoinPINVOKE.set_coin__Transaction_InnerHash(swigCPtr, SWIGTYPE_p_GoUint8_.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = skycoinPINVOKE.get_coin__Transaction_InnerHash(swigCPtr);
      SWIGTYPE_p_GoUint8_ ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_GoUint8_(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_GoSlice_ Sigs {
    set {
      skycoinPINVOKE.set_coin__Transaction_Sigs(swigCPtr, SWIGTYPE_p_GoSlice_.getCPtr(value));
      if (skycoinPINVOKE.SWIGPendingException.Pending) throw skycoinPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_GoSlice_ ret = new SWIGTYPE_p_GoSlice_(skycoinPINVOKE.get_coin__Transaction_Sigs(swigCPtr), true);
      if (skycoinPINVOKE.SWIGPendingException.Pending) throw skycoinPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_GoSlice_ In {
    set {
      skycoinPINVOKE.set_coin__Transaction_In(swigCPtr, SWIGTYPE_p_GoSlice_.getCPtr(value));
      if (skycoinPINVOKE.SWIGPendingException.Pending) throw skycoinPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_GoSlice_ ret = new SWIGTYPE_p_GoSlice_(skycoinPINVOKE.get_coin__Transaction_In(swigCPtr), true);
      if (skycoinPINVOKE.SWIGPendingException.Pending) throw skycoinPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_GoSlice_ Out {
    set {
      skycoinPINVOKE.set_coin__Transaction_Out(swigCPtr, SWIGTYPE_p_GoSlice_.getCPtr(value));
      if (skycoinPINVOKE.SWIGPendingException.Pending) throw skycoinPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_GoSlice_ ret = new SWIGTYPE_p_GoSlice_(skycoinPINVOKE.get_coin__Transaction_Out(swigCPtr), true);
      if (skycoinPINVOKE.SWIGPendingException.Pending) throw skycoinPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public coin__Transaction() : this(skycoinPINVOKE.new_coin__Transaction(), true) {
  }

}

}
