//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace skycoin {

public class GoSlice : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GoSlice(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GoSlice obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GoSlice() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          skycoinPINVOKE.delete_GoSlice(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int isEqual(GoSlice slice) {
    int ret = skycoinPINVOKE.GoSlice_isEqual(swigCPtr, GoSlice.getCPtr(slice));
    return ret;
  }

  public void convertString(_GoString_ data) {
    skycoinPINVOKE.GoSlice_convertString(swigCPtr, _GoString_.getCPtr(data));
    if (skycoinPINVOKE.SWIGPendingException.Pending) throw skycoinPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setAtChar(char p, ulong i) {
    skycoinPINVOKE.GoSlice_setAtChar(swigCPtr, p, i);
  }

  public void getString(_GoString_ arg0) {
    skycoinPINVOKE.GoSlice_getString(swigCPtr, _GoString_.getCPtr(arg0));
  }

  public SWIGTYPE_p_void data {
    set {
      skycoinPINVOKE.set_GoSlice_data(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = skycoinPINVOKE.get_GoSlice_data(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public long len {
    set {
      skycoinPINVOKE.set_GoSlice_len(swigCPtr, value);
    } 
    get {
      long ret = skycoinPINVOKE.get_GoSlice_len(swigCPtr);
      return ret;
    } 
  }

  public long cap {
    set {
      skycoinPINVOKE.set_GoSlice_cap(swigCPtr, value);
    } 
    get {
      long ret = skycoinPINVOKE.get_GoSlice_cap(swigCPtr);
      return ret;
    } 
  }

  public GoSlice() : this(skycoinPINVOKE.new_GoSlice(), true) {
  }

}

}
