/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DefaultApi
            //Assert.IsInstanceOfType(typeof(DefaultApi), instance, "instance is a DefaultApi");
        }

        
        /// <summary>
        /// Test AddressCount
        /// </summary>
        [Test]
        public void AddressCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AddressCount();
            //Assert.IsInstanceOf<InlineResponse2001> (response, "response is InlineResponse2001");
        }
        
        /// <summary>
        /// Test AddressUxouts
        /// </summary>
        [Test]
        public void AddressUxoutsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string address = null;
            //var response = instance.AddressUxouts(address);
            //Assert.IsInstanceOf<List<InlineResponse200>> (response, "response is List<InlineResponse200>");
        }
        
        /// <summary>
        /// Test BalanceGet
        /// </summary>
        [Test]
        public void BalanceGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string addrs = null;
            //var response = instance.BalanceGet(addrs);
            //Assert.IsInstanceOf<InlineResponse2002> (response, "response is InlineResponse2002");
        }
        
        /// <summary>
        /// Test BalancePost
        /// </summary>
        [Test]
        public void BalancePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string addrs = null;
            //var response = instance.BalancePost(addrs);
            //Assert.IsInstanceOf<InlineResponse2002> (response, "response is InlineResponse2002");
        }
        
        /// <summary>
        /// Test Block
        /// </summary>
        [Test]
        public void BlockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? verbose = null;
            //string hash = null;
            //int? seq = null;
            //var response = instance.Block(verbose, hash, seq);
            //Assert.IsInstanceOf<InlineResponse2003> (response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test BlockchainMetadata
        /// </summary>
        [Test]
        public void BlockchainMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BlockchainMetadata();
            //Assert.IsInstanceOf<InlineResponse2004> (response, "response is InlineResponse2004");
        }
        
        /// <summary>
        /// Test BlockchainProgress
        /// </summary>
        [Test]
        public void BlockchainProgressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.BlockchainProgress();
            //Assert.IsInstanceOf<InlineResponse2005> (response, "response is InlineResponse2005");
        }
        
        /// <summary>
        /// Test BlocksGet
        /// </summary>
        [Test]
        public void BlocksGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? verbose = null;
            //int? start = null;
            //int? end = null;
            //string seqs = null;
            //var response = instance.BlocksGet(verbose, start, end, seqs);
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
        
        /// <summary>
        /// Test BlocksPost
        /// </summary>
        [Test]
        public void BlocksPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? verbose = null;
            //int? start = null;
            //int? end = null;
            //string seqs = null;
            //var response = instance.BlocksPost(verbose, start, end, seqs);
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
        
        /// <summary>
        /// Test CoinSupply
        /// </summary>
        [Test]
        public void CoinSupplyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.CoinSupply();
            
        }
        
        /// <summary>
        /// Test Csrf
        /// </summary>
        [Test]
        public void CsrfTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Csrf();
            //Assert.IsInstanceOf<InlineResponse2007> (response, "response is InlineResponse2007");
        }
        
        /// <summary>
        /// Test DefaultConnections
        /// </summary>
        [Test]
        public void DefaultConnectionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DefaultConnections();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test ExplorerAddress
        /// </summary>
        [Test]
        public void ExplorerAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string address = null;
            //var response = instance.ExplorerAddress(address);
            //Assert.IsInstanceOf<List<InlineResponse2008>> (response, "response is List<InlineResponse2008>");
        }
        
        /// <summary>
        /// Test Health
        /// </summary>
        [Test]
        public void HealthTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Health();
            //Assert.IsInstanceOf<InlineResponse2009> (response, "response is InlineResponse2009");
        }
        
        /// <summary>
        /// Test InjectTransaction
        /// </summary>
        [Test]
        public void InjectTransactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string rawtx = null;
            //instance.InjectTransaction(rawtx);
            
        }
        
        /// <summary>
        /// Test LastBlocks
        /// </summary>
        [Test]
        public void LastBlocksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? verbose = null;
            //int? num = null;
            //var response = instance.LastBlocks(verbose, num);
            //Assert.IsInstanceOf<InlineResponse2006> (response, "response is InlineResponse2006");
        }
        
        /// <summary>
        /// Test NetworkConnection
        /// </summary>
        [Test]
        public void NetworkConnectionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string addr = null;
            //var response = instance.NetworkConnection(addr);
            //Assert.IsInstanceOf<InlineResponse20010> (response, "response is InlineResponse20010");
        }
        
        /// <summary>
        /// Test NetworkConnections
        /// </summary>
        [Test]
        public void NetworkConnectionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string states = null;
            //string direction = null;
            //var response = instance.NetworkConnections(states, direction);
            //Assert.IsInstanceOf<List<InlineResponse20010>> (response, "response is List<InlineResponse20010>");
        }
        
        /// <summary>
        /// Test NetworkConnectionsDisconnect
        /// </summary>
        [Test]
        public void NetworkConnectionsDisconnectTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.NetworkConnectionsDisconnect(id);
            
        }
        
        /// <summary>
        /// Test NetworkConnectionsExchange
        /// </summary>
        [Test]
        public void NetworkConnectionsExchangeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.NetworkConnectionsExchange();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test NetworkConnectionsTrust
        /// </summary>
        [Test]
        public void NetworkConnectionsTrustTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.NetworkConnectionsTrust();
            //Assert.IsInstanceOf<List<string>> (response, "response is List<string>");
        }
        
        /// <summary>
        /// Test OutputsGet
        /// </summary>
        [Test]
        public void OutputsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string address = null;
            //string hash = null;
            //var response = instance.OutputsGet(address, hash);
            //Assert.IsInstanceOf<InlineResponse20011> (response, "response is InlineResponse20011");
        }
        
        /// <summary>
        /// Test OutputsPost
        /// </summary>
        [Test]
        public void OutputsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string address = null;
            //string hash = null;
            //var response = instance.OutputsPost(address, hash);
            //Assert.IsInstanceOf<InlineResponse20011> (response, "response is InlineResponse20011");
        }
        
        /// <summary>
        /// Test PendingTxs
        /// </summary>
        [Test]
        public void PendingTxsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? verbose = null;
            //var response = instance.PendingTxs(verbose);
            //Assert.IsInstanceOf<List<InlineResponse20012>> (response, "response is List<InlineResponse20012>");
        }
        
        /// <summary>
        /// Test Rawtx
        /// </summary>
        [Test]
        public void RawtxTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string txid = null;
            //instance.Rawtx(txid);
            
        }
        
        /// <summary>
        /// Test ResendUnconfirmedTxns
        /// </summary>
        [Test]
        public void ResendUnconfirmedTxnsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ResendUnconfirmedTxns();
            
        }
        
        /// <summary>
        /// Test Richlist
        /// </summary>
        [Test]
        public void RichlistTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string includeDistribution = null;
            //string n = null;
            //var response = instance.Richlist(includeDistribution, n);
            //Assert.IsInstanceOf<InlineResponse20013> (response, "response is InlineResponse20013");
        }
        
        /// <summary>
        /// Test Transaction
        /// </summary>
        [Test]
        public void TransactionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string txid = null;
            //bool? encoded = null;
            //bool? verbose = null;
            //var response = instance.Transaction(txid, encoded, verbose);
            //Assert.IsInstanceOf<InlineResponse20014> (response, "response is InlineResponse20014");
        }
        
        /// <summary>
        /// Test TransactionsGet
        /// </summary>
        [Test]
        public void TransactionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string addrs = null;
            //string confirmed = null;
            //bool? verbose = null;
            //var response = instance.TransactionsGet(addrs, confirmed, verbose);
            //Assert.IsInstanceOf<List<InlineResponse20014>> (response, "response is List<InlineResponse20014>");
        }
        
        /// <summary>
        /// Test TransactionsPost
        /// </summary>
        [Test]
        public void TransactionsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string addrs = null;
            //string confirmed = null;
            //bool? verbose = null;
            //var response = instance.TransactionsPost(addrs, confirmed, verbose);
            //Assert.IsInstanceOf<List<InlineResponse20014>> (response, "response is List<InlineResponse20014>");
        }
        
        /// <summary>
        /// Test Uxout
        /// </summary>
        [Test]
        public void UxoutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string uxid = null;
            //var response = instance.Uxout(uxid);
            //Assert.IsInstanceOf<InlineResponse200> (response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test VerifyAddress
        /// </summary>
        [Test]
        public void VerifyAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string address = null;
            //var response = instance.VerifyAddress(address);
            //Assert.IsInstanceOf<InlineResponse20022> (response, "response is InlineResponse20022");
        }
        
        /// <summary>
        /// Test Version
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.Version();
            
        }
        
        /// <summary>
        /// Test Wallet
        /// </summary>
        [Test]
        public void WalletTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.Wallet(id);
            //Assert.IsInstanceOf<InlineResponse20015> (response, "response is InlineResponse20015");
        }
        
        /// <summary>
        /// Test WalletBalance
        /// </summary>
        [Test]
        public void WalletBalanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.WalletBalance(id);
            //Assert.IsInstanceOf<InlineResponse2002> (response, "response is InlineResponse2002");
        }
        
        /// <summary>
        /// Test WalletCreate
        /// </summary>
        [Test]
        public void WalletCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string seed = null;
            //string label = null;
            //int? scan = null;
            //bool? encrypt = null;
            //string password = null;
            //var response = instance.WalletCreate(seed, label, scan, encrypt, password);
            //Assert.IsInstanceOf<InlineResponse20015> (response, "response is InlineResponse20015");
        }
        
        /// <summary>
        /// Test WalletDecrypt
        /// </summary>
        [Test]
        public void WalletDecryptTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string password = null;
            //var response = instance.WalletDecrypt(id, password);
            //Assert.IsInstanceOf<InlineResponse20015> (response, "response is InlineResponse20015");
        }
        
        /// <summary>
        /// Test WalletEncrypt
        /// </summary>
        [Test]
        public void WalletEncryptTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string password = null;
            //var response = instance.WalletEncrypt(id, password);
            //Assert.IsInstanceOf<InlineResponse20015> (response, "response is InlineResponse20015");
        }
        
        /// <summary>
        /// Test WalletFolder
        /// </summary>
        [Test]
        public void WalletFolderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string addr = null;
            //var response = instance.WalletFolder(addr);
            //Assert.IsInstanceOf<InlineResponse20021> (response, "response is InlineResponse20021");
        }
        
        /// <summary>
        /// Test WalletNewAddress
        /// </summary>
        [Test]
        public void WalletNewAddressTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string num = null;
            //string password = null;
            //var response = instance.WalletNewAddress(id, num, password);
            //Assert.IsInstanceOf<InlineResponse20016> (response, "response is InlineResponse20016");
        }
        
        /// <summary>
        /// Test WalletNewSeed
        /// </summary>
        [Test]
        public void WalletNewSeedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string entropy = null;
            //var response = instance.WalletNewSeed(entropy);
            //Assert.IsInstanceOf<InlineResponse20017> (response, "response is InlineResponse20017");
        }
        
        /// <summary>
        /// Test WalletRecover
        /// </summary>
        [Test]
        public void WalletRecoverTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string seed = null;
            //string password = null;
            //var response = instance.WalletRecover(id, seed, password);
            //Assert.IsInstanceOf<InlineResponse20023> (response, "response is InlineResponse20023");
        }
        
        /// <summary>
        /// Test WalletSeed
        /// </summary>
        [Test]
        public void WalletSeedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string password = null;
            //var response = instance.WalletSeed(id, password);
            //Assert.IsInstanceOf<InlineResponse20017> (response, "response is InlineResponse20017");
        }
        
        /// <summary>
        /// Test WalletSpent
        /// </summary>
        [Test]
        public void WalletSpentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string dst = null;
            //string coins = null;
            //string password = null;
            //var response = instance.WalletSpent(id, dst, coins, password);
            //Assert.IsInstanceOf<InlineResponse20018> (response, "response is InlineResponse20018");
        }
        
        /// <summary>
        /// Test WalletTransactions
        /// </summary>
        [Test]
        public void WalletTransactionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //bool? verbose = null;
            //var response = instance.WalletTransactions(id, verbose);
            //Assert.IsInstanceOf<InlineResponse20019> (response, "response is InlineResponse20019");
        }
        
        /// <summary>
        /// Test WalletUnload
        /// </summary>
        [Test]
        public void WalletUnloadTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.WalletUnload(id);
            
        }
        
        /// <summary>
        /// Test WalletUpdate
        /// </summary>
        [Test]
        public void WalletUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string label = null;
            //instance.WalletUpdate(id, label);
            
        }
        
        /// <summary>
        /// Test Wallets
        /// </summary>
        [Test]
        public void WalletsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Wallets();
            //Assert.IsInstanceOf<List<InlineResponse20020>> (response, "response is List<InlineResponse20020>");
        }
        
    }

}
