/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.0
 * Contact: skycoin.doe@example.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2004Head
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse2004HeadTests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2004Head
        //private InlineResponse2004Head instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse2004Head
            //instance = new InlineResponse2004Head();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse2004Head
        /// </summary>
        [Test]
        public void InlineResponse2004HeadInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2004Head
            //Assert.IsInstanceOfType<InlineResponse2004Head> (instance, "variable 'instance' is a InlineResponse2004Head");
        }


        /// <summary>
        /// Test the property 'BlockHash'
        /// </summary>
        [Test]
        public void BlockHashTest()
        {
            // TODO unit test for the property 'BlockHash'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Test]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'PreviousBlockHash'
        /// </summary>
        [Test]
        public void PreviousBlockHashTest()
        {
            // TODO unit test for the property 'PreviousBlockHash'
        }
        /// <summary>
        /// Test the property 'Seq'
        /// </summary>
        [Test]
        public void SeqTest()
        {
            // TODO unit test for the property 'Seq'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'TxBodyHash'
        /// </summary>
        [Test]
        public void TxBodyHashTest()
        {
            // TODO unit test for the property 'TxBodyHash'
        }
        /// <summary>
        /// Test the property 'UxHash'
        /// </summary>
        [Test]
        public void UxHashTest()
        {
            // TODO unit test for the property 'UxHash'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
